Add SAI_SWITCH_ATTR_SWITCH_HARDWARE_INFO format for GB MDIO sysfs access
opencomputeproject/SAI pull request #1171
Opened 2020-12-08 23:39 UTC by sujinmkang

SAI_SWITCH_ATTR_SWITCH_HARDWARE_INFO is the right attribute to be used to provide the each Phy information

- SAI_SWITCH_ATTR_SWITCH_HARDWARE_INFO shall contain the interface_name and phy_id with “/” as the separator. 

- The data should be formatted as {intf_name}/{phy_id} : Ex) eth0/1

- GB Phy SAI is expected to parse the SAI_SWITCH_ATTR_SWITCH_HARDWARE_INFO to determine the phy_id along with interface name for each phySAI

2020-12-09 12:41 UTC, kcudnik commented
Fix aspell "sysfs", and also this seems like a information related only to gearbox not generic, other vendors can put any information they want there.

2020-12-10 23:43 UTC, lguohan approved these changes

2020-12-10 23:44 UTC, lguohan commented
@sujinmkang can you add the keyword into dictionary.

2021-01-04 11:52 UTC, kcudnik commented
```WARNING: Word 'SysFS' is misspelled saiswitch.h 1447:     * Example: Like PCI location, I2C address, MDIO bus SysFS information etc.
```
just add SysFS to aspell dictionary in meta dir

2021-01-04 18:35 UTC, kcudnik approved these changes

2021-01-14 16:53 UTC, rlhui commented
@prafull-brcm , @apogedik - would you please help review/approve?  Thanks.

2021-01-15 04:36 UTC, prafull-brcm requested changes
For non sysfs MDIO, I think this statement should also be added as it is not always we are using mdio sysfs.
For non Sysfs MDIO, only phy_id should be provided.

2021-01-15 04:36 UTC, prafull-brcm commented on inc/saiswitch.h
> +     * For the MDIO SysFS driver support, the interface name and phy_id should be
For non sysfs MDIO, I think this statement should also be added as it is not always we are using mdio sysfs.
For non Sysfs MDIO, only phy_id should be provided.

2021-02-09 06:47 UTC, prafull-brcm approved these changes
Changes looks good to me.

2021-02-22 04:43 UTC, merged