Tunnel UDP SRC PORT security
opencomputeproject/SAI pull request #1455
Opened 2022-03-24 07:20 UTC by marian-pritsak

Question to community: Is this feature supported natively on your ASICs, or is it rather something that will have to be done with ACL?

2022-03-24 17:40 UTC, kcudnik requested changes

2022-03-24 17:40 UTC, kcudnik commented on inc/saitunnel.h
> +     * @type sai_bool
bool

2022-04-25 14:53 UTC, kcudnik approved these changes

2022-04-28 06:48 UTC, rlhui commented
@JaiOCP , @ashutosh-agrawal - please help review.

2022-05-05 16:05 UTC, ashutosh-agrawal approved these changes

2022-05-19 15:46 UTC, rlhui commented
@marian-pritsak  - please resolve the DCO error, so that we can merge this, thanks.

2022-06-23 16:26 UTC, rlhui commented
@marian-pritsak , please address DCO error. Thanks.

2022-07-14 04:21 UTC, rlhui commented
@marian-pritsak  - reminder to resolve DCO error

2022-07-21 16:11 UTC, marian-pritsak commented on inc/saitunnel.h
> +    SAI_TUNNEL_ATTR_VXLAN_UDP_SPORT_SECURITY,
Done

2022-07-21 17:53 UTC, kcudnik approved these changes

2022-08-11 16:38 UTC, merged