Bulk API for setting Port Attributes
opencomputeproject/SAI pull request #1460
Opened 2022-03-24 21:09 UTC by JaiOCP

Bulk API for setting Port Attributes

2022-03-25 11:59 UTC, kcudnik approved these changes

2022-04-01 17:20 UTC, kcudnik requested changes

2022-04-01 17:20 UTC, kcudnik commented on inc/saiport.h
> +    sai_bulk_object_remove_fn              remove_ports_attribute;
should be create_ports and remove ports

2022-04-01 18:53 UTC, JaiOCP commented
@kcudnik 
https://github.com/opencomputeproject/SAI/commit/03f93b6bc04cde534bc786e9d78d9d60abe6a251

2022-04-02 09:47 UTC, kcudnik approved these changes

2022-04-05 05:09 UTC, rlhui approved these changes

2022-04-05 05:10 UTC, merged