Adaptive Routing and Switching
opencomputeproject/SAI pull request #1681
Opened 2022-12-16 21:12 UTC by JaiOCP

This PR introduces a new concept where forwarding is done based parametric quality computation of the forwarding paths.

Following PRs have been closed because of enum churn but have all the audit trail of review comments. Please refer to them for history.
https://github.com/opencomputeproject/SAI/pull/1658
https://github.com/opencomputeproject/SAI/pull/1595

2022-12-16 21:27 UTC, JaiOCP commented
@ashutosh-agrawal @eddyk-nvidia @marian-pritsak @rck-innovium @lguohan @rlhui 

Please review. This is final update based on all the feedbacks.

2022-12-16 22:00 UTC, tushar-ty requested changes

2023-01-02 06:20 UTC, eddyk-nvidia commented
> @ashutosh-agrawal @eddyk-nvidia @marian-pritsak @rck-innovium @lguohan @rlhui
> 
> Please review. This is final update based on all the feedbacks.

@marian-pritsak and me are OK with the final release. Thanks

2023-01-03 01:05 UTC, ashutosh-agrawal commented
> @ashutosh-agrawal @eddyk-nvidia @marian-pritsak @rck-innovium @lguohan @rlhui
> 
> Please review. This is final update based on all the feedbacks.

I'm okay with the proposal too.

2023-01-06 19:44 UTC, JaiOCP commented on doc/ARS/Adaptive-Routing-and-Switching.md
> +| Flowlet    | contagious subsequence of packets within a macro flow separated by an idle time interval    |
https://github.com/opencomputeproject/SAI/pull/1681/commits/c30f206e2feb7e2c75853bbdfbbb1626657a4ec7

2023-01-06 19:44 UTC, JaiOCP commented on doc/ARS/Adaptive-Routing-and-Switching.md
> +*random path with out considering path quality*
https://github.com/opencomputeproject/SAI/pull/1681/commits/c30f206e2feb7e2c75853bbdfbbb1626657a4ec7

2023-01-06 19:44 UTC, JaiOCP commented on doc/ARS/Adaptive-Routing-and-Switching.md
> +*Computed value need to be quantized into buckets or bands for easier intepretation*
https://github.com/opencomputeproject/SAI/pull/1681/commits/c30f206e2feb7e2c75853bbdfbbb1626657a4ec7

2023-01-06 19:46 UTC, JaiOCP commented
Thank you @marian-pritsak @eddyk-nvidia @ashutosh-agrawal @rck-innovium for providing your inputs. 
Can you please approve the PR for merge.

2023-01-07 09:09 UTC, eddyk-nvidia approved these changes

2023-01-18 21:54 UTC, JaiOCP commented
@ashutosh-agrawal @rck-innovium Gentle reminder to approve this PR

2023-01-19 05:13 UTC, ashutosh-agrawal approved these changes

2023-02-15 19:34 UTC, JaiOCP commented
@rck-innovium Please approve

2023-02-23 16:21 UTC, merged