Add ingress_acl and egress_acl attributes to tunnel object
opencomputeproject/SAI pull request #1908
Opened 2023-09-28 00:12 UTC by kperumalbfn

Add SAI_TUNNEL_ATTR_INGRESS_ACL and SAI_TUNNEL_ATTR_EGRESS_ACL attributes to tunnel object.

2023-09-28 00:38 UTC, kperumalbfn commented
@marian-pritsak @mvenkat12 Could you review this PR

2023-09-28 06:14 UTC, rck-innovium commented
@kperumalbfn 

In order to align with the current SAI model, we should define a new bindpoint type in sai\_acl\_bind\_point\_type\_t, say SAI\_ACL\_BIND\_POINT\_TYPE\_TUNNEL.

Only the ACL tables/groups created with this bindpoint type should be allowed to be bound to SAI\_TUNNEL\_ATTR\_\[INGRESS/EGRESS\]\_ACL

2023-09-28 06:14 UTC, rck-innovium requested changes
Please include the required bindpoint type additions.

2023-10-15 22:53 UTC, srikrishnagopu commented
@kperumalbfn Couple of suggestions/questions:

- Can we please more description to the PR on the motivation and usecases so that it will be helpful to refer it in the future ?
- Any packet which goes through tunnel decap on this tunnel object will go through ingress ACL and any packet which goes through the tunnel encap on this tunnel object on this tunnel object will go through egress ACL ?
- Given that ACL already has the fields to match on outer and inner packet fields, any inputs on why this bindpoint is required ?

2023-10-15 22:55 UTC, srikrishnagopu reviewed
@kperumalbfn  Few suggestions/questions:

- Can we please more description to the PR on the motivation and usecases so that it will be helpful to refer it in the future ?
- Any packet which goes through tunnel decap on this tunnel object will go through ingress ACL and any packet which goes through the tunnel encap on this tunnel object on this tunnel object will go through egress ACL ?
- Given that ACL already has the fields to match on outer and inner packet fields, any inputs on why this bindpoint is required ?

2023-10-16 14:51 UTC, kcudnik approved these changes
approve just for code syntax ok

2023-10-16 20:09 UTC, srikrishnagopu approved these changes
Thanks a lot @kperumalbfn  for the clarification. Please update the PR description. 

SAI changes LGTM. We can discuss in the sai meeting if not discussed already.

2023-12-13 22:04 UTC, kperumalbfn commented
Will close this PR. To support Smartswitch usecases, we will add a new SAI ACL attribute to match on 'TUNNEL_TERMINATE_FLAG' to support different ACL actions for 'tunnel_terminate_flag=false+packet_fields' and 'tunnel_terminate_flag=true+packet_fields'.

2023-12-13 22:04 UTC, closed without merging