sFlow Truncation support
opencomputeproject/SAI pull request #2065
Opened 2024-08-13 17:55 UTC by rck-innovium

Support truncation for SAI\_SAMPLEPACKET\_TYPE\_SLOW\_PATH.

2024-08-15 16:04 UTC, marian-pritsak requested changes

2024-08-15 16:04 UTC, marian-pritsak commented on inc/saisamplepacket.h
> +     * This value takes effect when SAI_SAMPLEPACKET_ATTR_TRUNCATE_ENABLE is True.
Use @condition annotation for this

2024-08-15 16:07 UTC, rck-innovium commented on doc/Samplepacket/SAI-Proposal-Samplepacket_truncation.md
> ++    SAI_SAMPLEPACKET_ATTR_TRUNCATE_SIZE,
Qn from @JaiOCP during review on Aug-15-2024:  In SAI\_SAMPLEPACKET\_TYPE\_MIRROR\_SESSION, define the behavior when both SAI\_SAMPLEPACKET\_ATTR\_TRUNCATE\_SIZE and SAI\_MIRROR\_SESSION\_ATTR\_TRUNCATE\_SIZE are given. 

The explanation was to follow #1082: Use SAI\_SAMPLEPACKET\_ATTR\_TRUNCATE\_SIZE if we want to have the truncation specific to a port, and use SAI\_MIRROR\_SESSION\_ATTR\_TRUNCATE\_SIZE if we want the same truncation for all the ports using the same mirror session object.

Jai wanted to do more investigations and get back if the above behavior is agreeable.

2024-08-15 16:56 UTC, rck-innovium commented on inc/saisamplepacket.h
> +     * This value takes effect when SAI_SAMPLEPACKET_ATTR_TRUNCATE_ENABLE is True.
@marian-pritsak  Done

2024-08-16 16:35 UTC, kcudnik approved these changes

2024-09-10 17:19 UTC, marian-pritsak approved these changes

2024-09-10 19:15 UTC, JaiOCP approved these changes
Looks Good

2024-09-19 17:06 UTC, rlhui approved these changes

2024-09-19 17:06 UTC, merged